[phases.setup]
nixPkgs = ["nodejs", "chromium"]

[phases.install]
cmds = [
  "export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true",
  "npm install --production --ignore-scripts"
]

[start]
cmd = "node telegram_bot.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

